apiVersion: apps/v1
kind: Deployment
metadata:
  name: failed-liveness-probe
spec:
  replicas: 1
  selector:
    matchLabels:
      app: failed-liveness-probe
  template:
    metadata:
      labels:
        app: failed-liveness-probe
    spec:
      containers:
        - name: app
          image: nginx:1.25-alpine
          ports:
            - containerPort: 80
          resources:
            requests:
              cpu: 50m
              memory: 64Mi
          livenessProbe:
            httpGet:
              path: /healthz
              port: 80
            initialDelaySeconds: 2
            periodSeconds: 5
            failureThreshold: 3
